# Site settings
title: Chris Singer
email: ccsinger@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A land of code, coffee, but practically no common sense.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tremulaes.com" # the base hostname & protocol for your site
twitter_username: tremulaes
github_username:  secade

# Build settings
markdown: kramdown
